# ==========================================
# 1. Cấu hình thông tin kết nối PostgreSQL (Neon.tech)
# ==========================================
spring.datasource.url=jdbc:postgresql://ep-noisy-shape-azxv286d.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_7cPevGC9lpKJ
spring.datasource.driverClassName=org.postgresql.Driver

# Ép kiểu mã hóa tiếng Việt UTF-8
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

# ==========================================
# 2. Cấu hình Hibernate (Công cụ ánh xạ CSDL)
# ==========================================
# 'update': Tự động tạo và cập nhật cấu trúc bảng khi Entity thay đổi
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Hiển thị câu lệnh SQL thực tế trên Terminal để dễ debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Khai báo loại cơ sở dữ liệu để Spring tối ưu câu lệnh cho PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# 3. Cấu hình hiển thị lỗi API (Spring Boot & Security)
# ==========================================
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always